version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: dockerize -wait tcp://db:5432 -timeout 90s
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/opt
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
